services:
  db:
    image: postgres:13
    restart: always
    container_name: currency-db
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - '5454:5432'
